name: Feature request
description: Request a feature.
title: "Feature: "
labels: ["feature"]
assignees:
  - elRatto21
body:
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: request
    attributes:
      label: What do you want to see in blunder.io?
      placeholder: Tell us what feature you want to have in blunder.io.
    validations:
      required: true